name: Build Image
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: koala9527/hyperf_spider_admin@main
      with:
        name: koala/hyperf_spider_admin
        username: ${{ secrets.ALI_DOCKER_USERNAME }}
        password: ${{ secrets.ALI_DOCKER_USERNAME }}
        tag_names: true
        cache: true
        repository: registry.cn-shenzhen.aliyuncs.com/koala9527/koala
        tag_with_ref: true

